import React, { useState } from "react";
import {
  X,
  Info,
  Activity,
  Radio,
  Globe,
  MessageSquare,
  Paperclip,
  Send,
  Trash2,
  CheckCircle,
  FileText,
  Code,
  Database,
  ChevronDown,
} from "lucide-react";
import { policyImpactColor } from "../shared/Theme";

const IncidentDrawer = ({
  ticket,
  onClose,
  onDelete,
  onResolve,
  onUpdateTicket,
  onViewRawLog,
  isDark,
  colors,
}) => {
  const [comment, setComment] = useState("");
  const [expandedTraceStep, setExpandedTraceStep] = useState(null);
  const [history, setHistory] = useState([
    {
      user: "System",
      text: "Alert generated by Policy Engine (Rule: DLP-01).",
      time: "2h ago",
    },
    {
      user: "Faisal",
      text: "Investigating the payload. Looks like a false positive.",
      time: "1h ago",
    },
  ]);
  const handleSend = () => {
    if (!comment.trim()) return;
    setHistory([...history, { user: "Me", text: comment, time: "Just now" }]);
    setComment("");
  };
  const traceSteps = [
    {
      id: "init",
      title: "Source Initiated",
      status: "pass",
      time: "0ms",
      details: "Agent 'n8n_billing_bot' initiated request via gRPC.",
    },
    {
      id: "mtls",
      title: "mTLS Handshake",
      status: "pass",
      time: "5ms",
      details: "TLS 1.3 Established. Cipher: AES_256_GCM.",
    },
    {
      id: "dlp",
      title: "DLP Policy Scan",
      status: "fail",
      time: "42ms",
      details: "Blocked: Credit Card pattern detected in JSON body.",
    },
    {
      id: "dest",
      title: "Destination Reach",
      status: "blocked",
      time: "--",
      details: "Upstream (45.33.22.11) not reached.",
    },
  ];
  const optionClass = isDark
    ? "bg-[#14161B] text-gray-300"
    : "bg-white text-gray-800";

  return (
    <div
      className="fixed inset-0 z-[200] flex justify-end bg-black/50 backdrop-blur-sm animate-in fade-in duration-200"
      onClick={onClose}
    >
      <div
        className={`w-[700px] h-full shadow-2xl flex flex-col border-l ${
          colors.border
        } ${
          isDark ? "bg-[#0B0C10]" : "bg-white"
        } animate-in slide-in-from-right duration-300`}
        onClick={(e) => e.stopPropagation()}
      >
        <div
          className={`px-6 py-5 border-b ${colors.border} flex justify-between items-start ${colors.headerBg}`}
        >
          <div>
            <div className="flex items-center gap-3 mb-2">
              <span className="font-mono text-xs opacity-50">{ticket.id}</span>
              <div
                className={`relative h-6 flex items-center border px-2 ${policyImpactColor(
                  ticket.tag
                )}`}
              >
                <select
                  value={ticket.tag}
                  onChange={(e) =>
                    onUpdateTicket(ticket.id, { tag: e.target.value })
                  }
                  className="appearance-none bg-transparent outline-none pr-4 text-[10px] font-bold uppercase tracking-wider cursor-pointer z-10"
                >
                  <option className={optionClass} value="Critical">
                    Critical
                  </option>
                  <option className={optionClass} value="High">
                    High
                  </option>
                  <option className={optionClass} value="Medium">
                    Medium
                  </option>
                  <option className={optionClass} value="Low">
                    Low
                  </option>
                </select>
                <ChevronDown
                  size={12}
                  className="absolute right-2 opacity-50 pointer-events-none"
                />
              </div>
            </div>
            <h2
              className={`text-xl font-bold ${colors.textPrimary} leading-tight`}
            >
              {ticket.title}
            </h2>
          </div>
          <div className="flex gap-2">
            <button
              onClick={onViewRawLog}
              className={`px-3 py-1.5 border ${colors.border} text-xs font-bold ${colors.textSecondary} hover:${colors.textPrimary} transition-colors flex items-center gap-2`}
            >
              <FileText size={14} /> View Log
            </button>
            <button onClick={onClose} className={`p-2 ${colors.hover}`}>
              <X size={20} />
            </button>
          </div>
        </div>
        <div
          className={`flex-1 overflow-y-auto p-6 space-y-8 ${
            isDark ? "text-gray-300" : "text-gray-700"
          }`}
        >
          <div
            className={`p-4 border text-sm leading-relaxed ${colors.border} ${
              isDark
                ? "bg-blue-500/5 text-blue-100"
                : "bg-blue-50 text-blue-900"
            }`}
          >
            <div className="flex items-start gap-3">
              <Info size={16} className="mt-0.5 shrink-0" />
              <div>
                <span className="font-bold block mb-1">AI Summary</span> This
                incident was triggered by a{" "}
                <strong>Regex Match (Credit Card)</strong> on an outbound
                request from an internal finance bot. The destination IP is
                outside the allowed VPC.
              </div>
            </div>
          </div>
          <div>
            <h4 className="text-xs font-bold uppercase tracking-wider mb-4 flex items-center gap-2">
              <Activity size={14} className="text-blue-500" /> Full Request
              Trace
            </h4>
            <div className="space-y-0">
              {traceSteps.map((step, i) => {
                const isExpanded = expandedTraceStep === step.id;
                const isLast = i === traceSteps.length - 1;
                return (
                  <div key={step.id} className="flex gap-4">
                    <div className="flex flex-col items-center w-6 shrink-0 relative">
                      {/* ROUNDED DOTS */}
                      <div
                        className={`relative z-10 w-3 h-3 rounded-full border-2 bg-black mt-3 ${
                          step.status === "pass"
                            ? "border-green-500"
                            : step.status === "fail"
                            ? "border-red-500"
                            : "border-gray-500"
                        }`}
                      ></div>
                      {!isLast && (
                        <div
                          className={`absolute top-5 bottom-[-16px] w-0.5 ${
                            isDark ? "bg-gray-800" : "bg-gray-300"
                          }`}
                        ></div>
                      )}
                    </div>
                    <div className="flex-1 pb-4">
                      <div
                        onClick={() =>
                          setExpandedTraceStep(isExpanded ? null : step.id)
                        }
                        className={`cursor-pointer flex items-center justify-between p-3 border ${
                          colors.border
                        } ${
                          isExpanded
                            ? isDark
                              ? "bg-white/5"
                              : "bg-gray-100"
                            : "hover:bg-white/5"
                        } transition-all`}
                      >
                        <div className="flex items-center gap-3">
                          <span
                            className={`text-xs font-bold ${
                              step.status === "fail"
                                ? "text-red-500"
                                : colors.textPrimary
                            }`}
                          >
                            {step.title}
                          </span>
                        </div>
                        <span className="font-mono text-[10px] opacity-50">
                          {step.time}
                        </span>
                      </div>
                      {isExpanded && (
                        <div
                          className={`mt-2 p-4 border ${colors.border} ${
                            isDark ? "bg-[#14161B]" : "bg-white"
                          } text-xs font-mono animate-in slide-in-from-top-2 duration-200`}
                        >
                          <div className="mb-2 font-bold opacity-70">
                            Log Output:
                          </div>
                          <div className="opacity-80 leading-relaxed">
                            {step.details}
                          </div>
                        </div>
                      )}
                    </div>
                  </div>
                );
              })}
            </div>
          </div>
          <div className="grid grid-cols-2 gap-4">
            <div className={`p-4 border ${colors.border}`}>
              <span className="text-[10px] uppercase opacity-50 font-bold block mb-1">
                Source Agent
              </span>
              <div className="font-mono text-sm font-bold flex items-center gap-2">
                <Radio size={14} />{" "}
                {ticket.assignee === "Unassigned"
                  ? "n8n_billing_bot"
                  : "unknown_agent"}
              </div>
            </div>
            <div className={`p-4 border ${colors.border}`}>
              <span className="text-[10px] uppercase opacity-50 font-bold block mb-1">
                Destination
              </span>
              <div className="font-mono text-sm font-bold flex items-center gap-2">
                <Globe size={14} /> 45.33.22.11 (CN)
              </div>
            </div>
          </div>
          <div>
            <h4 className="text-xs font-bold uppercase tracking-wider mb-4 flex items-center gap-2">
              <MessageSquare size={14} /> Investigation Notes
            </h4>
            <div className="space-y-4 pl-2">
              {history.map((msg, i) => (
                <div key={i} className="flex gap-3">
                  <div
                    className={`w-6 h-6 flex shrink-0 items-center justify-center text-[10px] font-bold text-white ${
                      msg.user === "System" ? "bg-purple-600" : "bg-blue-600"
                    }`}
                  >
                    {msg.user[0]}
                  </div>
                  <div>
                    <div className="flex items-center gap-2 mb-0.5">
                      <span className="text-xs font-bold">{msg.user}</span>
                      <span className="text-[10px] opacity-40">{msg.time}</span>
                    </div>
                    <p className="text-xs opacity-80 leading-relaxed">
                      {msg.text}
                    </p>
                  </div>
                </div>
              ))}
            </div>
          </div>
        </div>
        <div
          className={`p-4 border-t ${colors.border} ${
            isDark ? "bg-[#14161B]" : "bg-white"
          }`}
        >
          <div
            className={`flex items-center gap-2 p-2 border mb-4 ${
              colors.border
            } ${isDark ? "bg-black/20" : "bg-gray-50"}`}
          >
            <Paperclip
              size={16}
              className="opacity-50 cursor-pointer hover:opacity-100"
            />
            <input
              type="text"
              className="flex-1 bg-transparent outline-none text-xs"
              placeholder="Add a note..."
              value={comment}
              onChange={(e) => setComment(e.target.value)}
              onKeyDown={(e) => e.key === "Enter" && handleSend()}
            />
            <button
              onClick={handleSend}
              className="p-1.5 bg-blue-600 text-white hover:bg-blue-700"
            >
              <Send size={12} />
            </button>
          </div>
          <div className="flex justify-between items-center">
            <button
              onClick={() => onDelete(ticket.id)}
              className="text-red-500 text-xs font-bold hover:underline flex items-center gap-2"
            >
              <Trash2 size={12} /> Delete
            </button>
            <div className="flex gap-2">
              <button
                className={`px-4 py-2 border ${colors.border} text-xs font-bold hover:bg-gray-500/10`}
              >
                Action...
              </button>
              <button
                onClick={() => onResolve(ticket.id)}
                className="px-4 py-2 bg-green-600 hover:bg-green-700 text-white text-xs font-bold flex items-center gap-2 shadow-lg"
              >
                <CheckCircle size={14} /> Resolve
              </button>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default IncidentDrawer;
